/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package leaky.java.app;

import java.util.ArrayList;
import java.util.Map;
import java.util.List;

import com.gremlin.failureflags.*;

public class App {
    public static String getGreeting() {
        return "Hello World! ";
    }

    public static void main(String[] args) {

        FailureFlags gremlin = new GremlinFailureFlags();
        Experiment[] activeExperiments;
        
        final List<Integer> NUMBERS = new ArrayList<>();
        for (int i = 1; i > 0; i++) {
            activeExperiments = gremlin.invoke(new FailureFlag("sample-java-ff", Map.of("method", "GET")));
            if (activeExperiments != null && activeExperiments.length > 0){
                NUMBERS.add(i);
                System.out.println("Leaking the Number array, size is now "+NUMBERS.size());
            } else {
            // if there is no experiment then do this
                System.out.println(getGreeting()+i);
            }
            try {
                Thread.sleep(500);
            } catch (InterruptedException ie) {
                System.out.println("Thread Execution Interrupted");
            }
        }
    }
}
